=== greatestview/x2flickr/trunk/x2server/DEV/x2request.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT x2 (source, thumbset?)>
	<!ELEMENT source (photo, data?)>
		<!ELEMENT photo (image+)>
		<!ATTLIST photo
			id CDATA #REQUIRED
		>
			<!ELEMENT image EMPTY>
			<!ATTLIST image
				url CDATA #REQUIRED
				type (square | thumbnail | small | medium | original) #IMPLIED
			>
		<!ELEMENT data (owner, title?, description?, tags?)>
			<!ELEMENT owner EMPTY>
			<!ATTLIST owner
				id CDATA #REQUIRED
				username CDATA #IMPLIED
				realname CDATA #IMPLIED
				location CDATA #IMPLIED
			>
			<!ELEMENT title (#PCDATA)>
			<!ELEMENT description (#PCDATA)>
			<!ELEMENT tags (tag+)>
				<!ELEMENT tag (#PCDATA)>
	<!ELEMENT thumbset (thumb+)>
	<!ATTLIST thumbset
		cols CDATA #REQUIRED
		rows CDATA #REQUIRED
	>
		<!ELEMENT thumb EMPTY>
		<!ATTLIST thumb
			id CDATA #REQUIRED
			url CDATA #REQUIRED
		>

=== greatestview/x2flickr/trunk/x2server/DEV/x2request.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE x2 SYSTEM "x2request.dtd">
<x2>
	<source>
		<photo id="15354646812">
			<image url="http://www.bla.de" type="square" />
			<image url="http://www.bla.de" type="medium" />
		</photo>
		<data>
			<owner id="12037949754@N01" username="Bees" realname="Cal Henderson" location="Bedford, UK" />
			<title>Titel</title>
			<description>Blablablbalblal</description>
			<tags>
				<tag>Bielefeld</tag>
				<tag>Borkum</tag>
			</tags>
		</data>
	</source>
	<thumbset cols="30" rows="40">
		<thumb id="135232466" url="http://www.bla.de" />
	</thumbset>
</x2>
